- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TasksNode.java
> fixed error when retrieving tasks (#2)

- src/main/resources/tkn.json
> updated tkn cli to 0.7.1 (#6)

- .travis.yml
- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
> Add integration stage

- src/main/java/com/redhat/devtools/intellij/common/actions/RefreshAction.java
- src/main/resources/META-INF/plugin.xml
> Added refresh action (#26)

- src/main/resources/tkn.json
> switched to tkn cli v0.8.0 (#38)

- CONTRIBUTING.md
- README.md
This is related to #8 
Add initial documentation
> added README and CONTRIBUTING files (#8)

- Jenkinsfile
> Fix repository in Jenkinsfile

- src/main/resources/META-INF/plugin.xml
> Fix vendor to match marketplace organization

- .github/workflows/IJ.yml
- .github/workflows/ci.yml
> CI workflow (master, pull requests)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/FollowLogsAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/LogsBaseAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/ShowLogsAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/DictionaryCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TknAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.java
Second part of the patch with the stuff to be changed before the release. Changed all log.error in warn.
> Changed from logger.error to warn

- src/main/resources/tknsnippets.json
This is related to #48 
We agreed to not handle these kind of issues because they are server errors so this PR only fixes the wrong snippets.
> fixed wrong snippets (#48)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
> fixed error first resource not selected by default (#56)

- src/main/resources/META-INF/plugin.xml
> Fix since based on Marketplace validation

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/OpenEditorAction.java
> focus editor on correct tab if already opened (#46)

- README.md
- src/main/resources/META-INF/plugin.xml
> Prepare for 0.0.1

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/DictionaryContributor.java
- src/main/resources/META-INF/plugin.xml
it resolves #93 
Completion code is only enabled on YAML file
> Activate completion code only on YAML files (#93)

- .github/workflows/IJ.yml
> Fix lowest IJ version following structure tree model switch

- src/main/java/com/redhat/devtools/intellij/tektoncd/WindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/resources/META-INF/plugin.xml
> Fix IJ compatibilities

- src/main/resources/tkn.json
> switched to 0.9.0 (#96)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartLastRunAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/resources/META-INF/plugin.xml
> added start last run action (#69)

- src/it/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonRootNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
This requires https://github.com/redhat-developer/intellij-common/pull/3
So in order to test it:
- get https://github.com/redhat-developer/intellij-common/pull/3
- run `gradlew publishToMavenLocal` in `intellij-common`
- either resync your intellij-tekton IJ project or run `gradlew runIde` from `intellij-tekton`
Fixes #104
> CLI download is broken with the new async tree model

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/ConditionDeserializer.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Resource.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/ResourceDeserializer.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Run.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/RunDeserializer.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
> use single object mapper (#45)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/OpenEditorAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/RefreshAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateClusterTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateEventListenerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/ClusterTriggerBindingNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/ClusterTriggerBindingsNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/EventListenerNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/EventListenersNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TriggerBindingNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TriggerBindingsNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TriggerTemplateNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TriggerTemplatesNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/tknsnippets.json
> added support for triggers (#74)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModelTest.java
- src/test/resources/task1.yaml
- src/test/resources/task2.yaml
- src/test/resources/task3.yaml
- src/test/resources/task4.yaml
- src/test/resources/task5.yaml
- src/test/resources/task6.yaml
- src/test/resources/task7.yaml
- src/test/resources/task8.yaml
- src/test/resources/task9.yaml
> Fix model to report several output resources

- .github/workflows/ci.yml
- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/RunDeserializer.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.form
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModelTest.java
- src/test/resources/pipeline1.yaml
- src/test/resources/pipeline2.yaml
> Added support for serviceAccount (#68)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/tknsnippets.json
- src/test/resources/pipeline1.yaml
- src/test/resources/pipeline2.yaml
- src/test/resources/task1.yaml
- src/test/resources/task2.yaml
- src/test/resources/task3.yaml
- src/test/resources/task4.yaml
- src/test/resources/task5.yaml
- src/test/resources/task6.yaml
- src/test/resources/task7.yaml
- src/test/resources/task8.yaml
- src/test/resources/task9.yaml
> Add support for v1beta1 (#78)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Workspace.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.form
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModelTest.java
- src/test/resources/task10.yaml
- src/test/resources/task11.yaml
- src/test/resources/task12.yaml
- src/test/resources/task13.yaml
- src/test/resources/task14.yaml
> added support for workspaces (#23)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
it resolves #83 
This needs https://github.com/redhat-developer/intellij-common/pull/9 to work
> added delete on multiple items (#83)

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
it resolves #123 
Now if the cluster is not running the user will be shown.
> Catch error if cluster is not reachable (#123)

- src/it/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
it resolves #109 partially
Fabric8 still doesn't support triggers so we also need to change that part as soon as fabric8 is updated.
> Switched to fabric8 tekton api to retrieve list objects and avoid using jsonpath (#109)

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
> fixed issue when starting pipeline/task using emptyDir as workspace

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
> Added delete action for runs + make existing delete actions handle multiple items

- src/main/resources/META-INF/plugin.xml
> Update contact email

- src/it/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonRootNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
Requires https://github.com/redhat-developer/intellij-common/pull/11
Fixes #20
> Add support for proxy

- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/ConditionAutoInsertHandler.java
This should fix the broken compilation with new Ij version
> Remove method deprecated in new IJ version

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartLastRunAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
> Show logs on Pipeline/Task start

- src/it/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/it/resources/pipeline1.yaml
- src/it/resources/task1.yaml
- src/main/resources/tkn.json
> Switch to cli 0.11.0 (#168)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/CancelAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/TreeExpansionListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/RefreshQueue.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
- src/main/resources/META-INF/plugin.xml
> added cancel action for runs (#137)

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructureTest.java
> Order taskruns by their starting time (#183)

- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/resources/pipeline1.yaml
- src/it/resources/pipelinerun1.yaml
- src/it/resources/task1.yaml
- src/it/resources/taskrun1.yaml
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/DeleteDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/RefreshQueue.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
it resolves #171 
Below some screenshot
Deleting a single task
Deleting a Pipeline
Deleting some resources
Deleting a lot of resources
> add option to delete all related resources of a pipeline/task (#171)

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliConditionTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineResourceTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/resources/condition1.yaml
- src/it/resources/pipelineresource1.yaml
- src/main/resources/tkn.json
it resolves #184 + some additional test
> switch to 0.12.0 (#184)

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/GraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/TektonFileEditorProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/TektonPreviewEditor.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/validation/KubernetesTypeInfo.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/validation/TektonSchemaProvider.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdaterTest.java
> Add preview editor for pipelines

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListenerList.json
> Update schemas with Trigger 0.8.0

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/RunDeserializer.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
> fix NPE when parsing run (#197)

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdater.java
> Protect graph updater against NPE

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Task.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Task.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
> Update schemas to Pipeline 0.16.0

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/BaseAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/ConditionAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/DictionaryContributor.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TaskAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TaskCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/YamlElementPatternHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
> Added code completion for taskRef (#153)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/CancelAction.java
> fix error when cluster is not connected (#211)

- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/ConditionCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/GeneralCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TaskCompletionProvider.java
> stop showing generic snippets with other code completion (#191)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModelTest.java
- src/test/resources/pipeline7.yaml
> add support for finally tasks in wizard (#204)

- src/main/resources/tkn.json
This is the first part related to #213. It should find tkn if present in PATH
> fixed regex to extract tkn version (#213)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/StartWizard.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModelTest.java
it resolves #190 
The wizard options panel looks like this. The `i` icon gives information regarding that option.
The result of specifying a prefix is shown below (e.g when the prefix is set to `first`
> Allow to specify a prefix for new *Run (#190)

- releng/gen.go
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/PipelineSchemasTest.java
- src/test/resources/schemas/pipeline-when.yaml
> Update schema generator to fix the WhenExpression type

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/AbstractPipelineGraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineRunGraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/TektonFileEditorProvider.java
> Add pipeline run diagram preview

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/addtrigger/TriggerStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
it resolves #236 and the issue we had with the `Add trigger` action. Until we implement Andre's solution (keep the watch active even if the node is collapsed) it is necessary.
> Extend watch feature for triggers and add refresh for Add trigger action

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/CancelAction.java
This is something i noticed yesterday. The cancel action wasn't visible when it should have. Fixed it.
> fix visibility issue cancel action

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/AbstractPipelineGraphUpdater.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdaterTest.java
- src/test/resources/schemas/pipeline-from.yaml
- src/test/resources/schemas/pipeline-runafter.yaml
- src/test/resources/schemas/pipeline-when-2tasks.yaml
> Update preview to support from and when relations

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/AbstractPipelineGraphUpdater.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdaterTest.java
- src/test/resources/schemas/pipeline-tasks-linked-by-parameter-array-value.yaml
- src/test/resources/schemas/pipeline-tasks-linked-by-parameter-string-value.yaml
> Update diagram when a task depends on the result of another

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListenerList.json
- And Tekton Pipelines 0.17.1 by transitivity
> Update schemas with Tekton Triggers 0.9.0

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliClusterTaskTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/resources/clustertask1.yaml
- src/main/resources/tkn.json
> update cli to 0.13.1 (#260)

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliClusterTaskTest.java
After merging the last 2 PRs i didn't noticed they were going to make a couple of integration tests to fail. This fixes it.
> fixed integration tests

- build.gradle
- src/test/java/com/redhat/devtools/intellij/tektoncd/hub/api/StatusApiTest.java
> Add generated Java API to Tekton Hub

- build.gradle
> Fix compilation errors

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Condition.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ConditionList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Task.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Task.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
> Update schemas to Tekton Pipeline 0.18.0

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModelFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/actions/ActionToRunModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
> extend start wizard to clusterTasks (#261)

- .github/workflows/ci.yml
- src/main/java/com/redhat/devtools/intellij/tektoncd/kubernetes/TektonHighlightInfoFilter.java
> NPE while opening files if Tekton plugin is installed

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/WindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonHubAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateEventListenerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/UIConstants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDialogTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItem.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubMarketplaceTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TektonVirtualFileManager.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConditionConfigurationModelTest.java
> Integrate TektonHub

- .github/workflows/IJ.yml
- build.gradle
- gradle.properties
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/resources/META-INF/plugin.xml
> Fix incompatibility with 2020.3

- .github/workflows/IJ.yml
- build.gradle
> Fix build for 2020.3

- .github/workflows/ci.yml
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliClusterTaskTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliClusterTriggerBindingTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTriggerBindingTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTriggerTemplateTest.java
- src/it/resources/clustertriggerbinding1.yaml
- src/it/resources/triggerbinding1.yaml
- src/it/resources/triggertemplate1.yaml
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TektonVirtualFileManager.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/resources/tkn.json
> Switch to tkn cli 0.15

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonHubAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDialogTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItem.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubMarketplaceTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/resources/META-INF/plugin.xml
it resolves #294
It works exactly as in vscode, the install button has a dropdown option that allow users to install a hub task as clusterTask
> Allow to install tektonhub tasks as clustertasks (#294)

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/AbstractPipelineGraphUpdater.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TektonVirtualFileManager.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/ui/editors/PipelineGraphUpdaterTest.java
depends on https://github.com/redhat-developer/intellij-common/issues/24
fixes #311
> use kubernetes-client 5.0.0 (#311)

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/addtrigger/TriggerStep.java
> fix UI glitch in add trigger wizard (#239)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsConfigurable.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsState.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsView.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/DeleteDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
> add basic preferences (#247)

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListenerList.json
> Update schemas from Tekton Triggers 0.11.1

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/ParametersStep.java
> update preview on changes (#315)

- build.gradle
> bumped dependency intellij-common to 0.0.1 (#342)

- build.gradle
> build: Update Kubernetes client to 5.0.2

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
extracted small methods and removed duplicate catching of IOException in order to reduce size of AddTriggerAction#actionPerformed (which is still quite large).
> refactor: extracted methods to reduce length of AddTriggerAction#actionPerformed

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonHubAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItem.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubMarketplaceTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
it resolves #330 
The tekton cli only works with tasks right now so i needed to edit/save the clustertask yaml "manually". 
We also need to agree on the conventional commits types because I used `feat` in this case but i'm not sure it's the correct one. This is not a real feature. It's more something that's useful for us for building future stuff.
I found this descriptions
```
feat: Add a new feature to the codebase (MINOR in semantic versioning).
fix: Fix a bug (equivalent to a PATCH in Semantic Versioning).
docs: Documentation changes.
style: Code style change (semicolon, indentation...).
refactor: Refactor code without changing public API.
perf: Update code performances.
test: Add test to an existing feature.
chore: Update something without impacting the user (ex: bump a dependency in …
```
> fix: add tektonHub label to new installed task/clustertask (#330)

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDialog.java
> fix(UI): add title to tektonhub dialog (#357)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
related to #331 
@lstocchi this is a refactoring that I have in #331 that allowed me to better read/maintain the code. It's tedious to bring forward when rebasing. I thus filed it as a separate change.
> refactor: extracted methods in AddTriggerAction for better maintanability

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelper.java
related to #331 
@lstocchi this is a refactoring that I have in #331 that allowed me to better read/maintain the code. It's tedious to bring forward when rebasing. I thus filed it as a separate change.
> refactor: extracted #executeTkn for better maintanability

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/MirrorStartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
extracted smaller methods to improved readability/maintainability (simplifies #331)
> refactor: extracted methods in StartAction for improved maintability

- releng/build.sh
- releng/gen.go
> chore: Add build script for schemas

- releng/go.mod
- releng/go.sum
- No schema changes, kept for historical
Fixes #386
Signed-off-by: Jeff MAURY <jmaury@rhel8.mshome.net>
> chore: Update schemas to Tekton Pipeline 0.22.0

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListenerList.json
> chore: Update schemas to Tekton Triggers 0.12.1

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/resources/start/add-task.yaml
- src/it/resources/start/sum-pipeline.yaml
- src/main/resources/tkn.json
> chore: update cli to 0.16.0 (#338)

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseWizard.java
> fix(UI): make cancel/help buttons visible on wizards for Mac (#365)

- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
> fix(UI): change text in save dialog and showing kind and name of updated resource (#347)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/DeleteDialog.java
it resolves #332 
The message in the delete dialog is like this now
> fix(UI): optimize delete dialog (#332)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/RefreshAction.java
> feat(UI): add Refresh action to root (#340)

- .github/workflows/IJ.yml
- build.gradle
> chore: Add 2021.1

- src/main/resources/META-INF/plugin.xml
> chore: add ids to actions and extension points (#399)

- src/it/java/com/redhat/devtools/intellij/tektoncd/TestUtils.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliEventListenerTest.java
- src/it/resources/eventlistener1.yaml
- src/main/resources/tkn.json
> chore: update cli to 0.17.2

- .github/workflows/IJ.yml
- .github/workflows/ci.yml
- .github/workflows/generator.yml
- CONTRIBUTING.md
- src/main/resources/META-INF/plugin.xml
> chore: Rename from master to main

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsConfigurable.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonRootNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructureTest.java
it resolves #370 
I faced https://github.com/redhat-developer/intellij-kubernetes/issues/180, not sure if we want to wait until a fix for that is released
> chore: add dependency to kubernetes plugin (#370)

- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/PipelineSchemasTest.java
- src/test/resources/schemas/pipeline-custom-task.yaml
> chore: verify custom tasks in pipelines

- .github/workflows/ci.yml
- build.gradle
> chore: bump common to 1.1.0

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Condition.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ConditionList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Task.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Task.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
> chore: Update schemas to Tekton Pipelines 0.24.1

- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Workspace.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/WorkspacesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/Utils.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/VirtualFileHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/RunConfigurationModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/BaseTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/WorkspaceTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructureTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/VirtualFileHelperTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilderTest.java
it resolves #398 + also adds support for creating new PVC (something vscode already had and IJ misses)
> feat(UI): add support for creating new PersistentVolumeClaim and/or VolumeClaimTemplate from start wizard and use them

- USAGE_DATA.md
- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/telemetry/TelemetryService.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
> fix: Add cluster information in telemetry login information

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/InstallFromHubAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDialogTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItem.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubMarketplaceTab.java
it fixes #361 and https://github.com/redhat-developer/intellij-tekton/issues/358
@adietish I changed how the buttons are created and now it is the same as in vscode. I don't use the combo anymore. Does it look better on your Mac? Is it easier to use?
This is how it looks in vscode
> fix: remove border that does not overlap to combobox (#361)

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Task.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Task.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
> chore: Update schemas to Tekton Pipelines 0.24.3

- releng/gen.go
- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
> chore: Update schemas to Tekton Pipelines 0.25.0

- .github/workflows/ci.yml
- build.gradle
> chore: Fix build

- releng/gen.go
- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/index.properties
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_ClusterInterceptor.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_ClusterInterceptorList.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListenerList.json
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/EventListenerSchemasTest.java
- src/test/resources/schemas/eventlistener-bitbucket-interceptor.yaml
- src/test/resources/schemas/eventlistener-cel-interceptor.yaml
- src/test/resources/schemas/eventlistener-github-interceptor.yaml
- src/test/resources/schemas/eventlistener-gitlab-interceptor.yaml
- src/test/resources/schemas/eventlistener1.yaml
> chore: Update schemas to Tekton Triggers 0.14.2

- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItemScore.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubItemScoreTest.java
> feat: recommend hub's tasks based on user project (#430)

- releng/build.sh
- releng/gen.go
- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/index.properties
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_Trigger.json
- src/main/resources/schemas/triggers.tekton.dev/v1alpha1_TriggerList.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_ClusterTriggerBinding.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_ClusterTriggerBindingList.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_EventListener.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_EventListenerList.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_Trigger.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_TriggerBinding.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_TriggerBindingList.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_TriggerList.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_TriggerTemplate.json
- src/main/resources/schemas/triggers.tekton.dev/v1beta1_TriggerTemplateList.json
> chore: Update schemas to Tekton Triggers 0.15.0

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.27.1

- src/main/resources/tkn.json
> chore: bump cli to 0.20.0 (#443)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateClusterTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateEventListenerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/resources/tknsnippets.json
- src/main/resources/triggerBindingSnippets.json
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilderTest.java
> fix: update triggers to use beta1 (#450)

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.28.1

- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/TestUtils.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelper.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelperTest.java
This should fix the version on the marketplace
> fix: use kubernetes-client 5.7.2 to fix fabric8io/kubernetes-client

- gradle.properties
- src/main/resources/META-INF/plugin.xml
> chore: Prepare for 0.13.0

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/WorkspacesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/SnippetHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/RunConfigurationModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/SnippetHelperTest.java
> fix: fix pvc/vct creation bug when starting pipeline or adding trigger

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/MutableTektonModelSynchronizer.java
it resolves #502 
it needs https://github.com/redhat-developer/intellij-common/pull/119 to work
> fix: prevent resetting whole tree when deleting run (#502)

- .github/workflows/IJ.yml
- .github/workflows/ci.yml
- build.gradle
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseWizard.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/inspector/FinallyReferencesInspectorTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/inspector/VariableReferenceInspectorTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/EventListenerSchemasTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/PipelineRunSchemasTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/PipelineSchemasTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/SchemasTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/TaskSchemasTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/schemas/TriggerTemplateSchemasTest.java
this works with https://github.com/redhat-developer/intellij-common/pull/123 and https://github.com/redhat-developer/intellij-common/pull/125
> chore: add 2021.3 verification

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.31.0

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/WorkspacesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
it resolves #504 
Now in the preview you can see new pvc/vct
> fix: show new vct/pvc in preview when starting a pipeline (#504)

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.32.1

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Triggers 0.18.0

- build.gradle
- src/main/resources/tkn.json
> feat: bump common dep and enable silentMode (#535)

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.33.2

- src/main/resources/tkn.json
> chore: bump cli to 0.23.0

- build.gradle
> chore: bump kubernetes-client to 5.7.4 (#540)

- .github/workflows/IJ.yml
- build.gradle
- gradle.properties
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubDetailsPageComponent.java
- src/main/resources/META-INF/plugin.xml
> chore: bump min IJ version to 2021.1 (#571)

- releng/go.mod
- releng/go.sum
Fixes #568
Signed-off-by: Jeff MAURY <jfmaury@redhat.com>
> chore: Update schemas to Tekton Triggers 0.20.1

- src/main/resources/META-INF/plugin.xml
> chore: update CRC link (#590)

- releng/go.mod
- releng/go.sum
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1alpha1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_Task.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1alpha1_TaskRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTask.json
- src/main/resources/schemas/tekton.dev/v1beta1_ClusterTaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Pipeline.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineList.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_PipelineRunList.json
- src/main/resources/schemas/tekton.dev/v1beta1_Task.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskList.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRun.json
- src/main/resources/schemas/tekton.dev/v1beta1_TaskRunList.json
Fixes #580
Signed-off-by: Jeff MAURY <jfmaury@redhat.com>
> chore: Update schemas to Tekton Pipelines 0.37.1

- build.gradle
> chore: bump common to 1.7.1 (#588)

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Triggers 0.20.2

- .github/workflows/IJ.yml
- build.gradle
> build: Add IntelliJ 2022.2

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.38.2

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Pipelines 0.38.3

- releng/go.mod
- releng/go.sum
> chore: Update schemas to Tekton Triggers 0.21.0

- releng/go.mod
- releng/go.sum
> chore(skip-release): Update schemas to Tekton Pipelines 0.40.2

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/bundle/CreateBundleDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/bundle/ListBundlesDialog.java
it resolves https://github.com/redhat-developer/intellij-tekton/issues/612
> fix: enable/disable deploy button in create bundle dialog

- build.gradle
related to https://github.com/redhat-developer/intellij-kubernetes/pull/516
fixes #620
> chore: bumped kubernetes-client to 5.12.4 (#620)

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
> fix: change core ns name when working with ocp cluster (#631)

- README.features.md
- README.md
Signed-off-by: Mohit Suman <mohit.skn@gmail.com>
> chore: fix readme descriptions

- gradle.properties
> chore(skip-release): bump to 1.4.0-SNAPSHOT

- Jenkinsfile
> chore(skip-release): add Luca to Jenkins submitter

- releng/go.mod
- releng/go.sum
> chore(skip-release): Update schemas to Tekton Pipelines 0.43.1

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/pipeline/CreatePipelineAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/task/CreateTaskAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/CreateTaskFromTaskSpecDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/SnippetHelper.java
- src/main/resources/tknsnippets.json
> feat: return v1 snippets if v1 pipelines is installed (#646)

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/AbstractPipelineGraphUpdater.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructureTest.java
> chore: bump k8s/tekton client to 6.4.0 (#641)
