- src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
it fixes #47 
When starting  a task or a pipeline by passing a value with an empty space in it (like `key=bla bla`) the execHelper quotes it  `"key=bla bla"`. When executing the command the tkncli interpret `"key` as it is the name to use and look for in the pipeline. It doesn't find it and it prints an error
> disabled handle quoting when executing command (#47)

- src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Input.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/StartDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
@jeffmaury this PR contains almost all changes we discussed yesterday. The only missing one is go from logger.error to logger.warn which i'll cover when this PR will be released.
The timestamp for saving a file works. If you can test it on your IDE it would be great because i don't know why when i click on the terminal my autosave doesn't get triggered.
You told me that validate the model before opening the start dialog wasn't needed right now (and just disable the start btn) but i prefer to go that way because it also helped me solving another issue and it helps having a cleaner code. Also if we need to tackle betav1 soon, this refactor was almost mandatory.
With this, the dialog is not shown if there are no inputs or outputs (the task is started automatically) and an error is shown if …
> Fix for first release - part 1

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/RefreshAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/LogsBaseAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/ParentableNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/PipelineRunsNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TaskRunNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TaskRunsNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
it fixes #81 
Couple of question here. 
First is which icon i should use? I left the pipeline icon as default here because i opened https://github.com/redhat-developer/intellij-tekton/issues/72 and i'll move to different icons with that PR. Do we agree to use the icons from vscode?
Second, in vscode under the pipelineruns root node they only show the pipelineruns without being able to expand them and see their taskrun. In this PR it works differently and you can expand a pipelinerun and see its children. Do i have to change it?
> Added Pipelineruns and Taskruns node as root

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/OpenEditorAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/TektonAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/clustertask/CreateClusterTaskAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/condition/CreateConditionAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/pipeline/CreatePipelineAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/resource/CreateResourceAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/task/CreateTaskAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateClusterTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateEventListenerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerBindingAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/triggers/CreateTriggerTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/SaveInEditorListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
it should resolve #102 
@jeffmaury From my tests it looks like there are many threads in queue when creating a new resource. All those threads are related to "find children for X node". From my understanding, when we try to find out which is the node to be refreshed, we go through all the tree and this invokes all these 'find children nodes' and based on the length of the tree it could take more or less time. This is also true as you say it takes only 10 sec for you to load the tree and in my case i have to wait more as in CRC i have lot of projects. Not sure if you know another way to fix this. I'm open to suggestion
> change how node is retrieved when creating new resource (#102)

- build.gradle
- src/main/java/com/redhat/devtools/intellij/tektoncd/WindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/TreeExpansionListener.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonRootNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
it resolves #73 
I had to use the latest version of fabric8 tekton as the previous ones had some issues with betav1 resources. Currently it doesn't support triggers.
I tried this patch by launching pipelines, deleting resources externally from ide and the tree refreshes quite good. Let me know what you think.
> added watch implementation to update tree automatically (#73)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/VirtualFileHelper.java
Long story short.
Based on https://www.jetbrains.org/intellij/sdk/docs/basics/virtual_file_system.html, the virtual file system encapsulates most of the activity related to files. One of the main goal is "Tracking file modifications and providing both old and new versions of the file content when a modification is detected" which is what we have in the current implementation.
Because the vfs manages a persistent snapshot of the user's hard disk what we were missing was to delete the file from the tmp folder and clean (refresh) the vfs so to delete the cached version.
> Fixed issue with cache when saving file (#136)

- .github/workflows/IJ.yml
- gradle.properties
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/BaseAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/ConditionAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/ConditionCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/DictionaryContributor.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/YamlElementPatternHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/ConditionNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/resources/META-INF/plugin.xml
it fixes #151 
The result of the PR is that the code completion menu shows this when called after a `conditionRef`
The first three options are actual conditions that exist in the cluster.
The other are the classic snippets we had before and are shown everywhere. I was tempted to remove them as we have schemas now, we should discuss about their life :laughing: 
This is the result by selecting one condition
It inserts all params/resources required by the condition so the user only needs to add their values.
> add code completion for conditions (#151)

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonRootNode.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
It resolves #144 
This is no a direct patch for #144 as i guess it was solved partially with #145 but i found another issue while testing it. 
I found out that if you changed the config on runtime the tree didn't refresh correctly. The problem is that the client (DefaultKubernetesClient) is initialized with a config but if it changes somehow, the tkn client doesn't get recreated. So if you are logged in as an admin and you change to a developer, the tkn client (initialized as admin) keeps working with that config.
To test it, i started crc without being logged in. Then i started the plugin. The tree contained only the root and a warning node to tell i wasn't logged in. Then i logged in as admin and then switched to developer. 
Before this patch the tree didn't refresh. With this, the tree …
> Fix issue when config change during runtime

- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/DictionaryContributor.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/RunAfterCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/YamlElementPatternHelper.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/completion/RunAfterCompletionProviderTest.java
- src/test/resources/completion/pipeline1.yaml
- src/test/resources/completion/pipeline2.yaml
- src/test/resources/completion/pipeline3.yaml
- src/test/resources/completion/pipeline4.yaml
it resolves #152 
This patch adds code completion for the runAfter tag. When the code completion is requested, it gets all tasks placed earlier in the pipeline than the one selected and shows them in the options. Below a demo.
> added runAfter code completion (#152)

- src/main/resources/tkn.json
Due to a performance issue with tkn cli 0.12.0, this patch switch the cli used by the plugin back to 0.11.0.
By testing again with the old cli, you can really see the difference in speed.
> switched back to 0.11.0

- src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructure.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tree/TektonTreeStructureTest.java
it resolves #202 
Now the taskrun nodes ordering depends on the position of the node.
Below the TASKRUNS node -> from newest to oldest
Below a TASK node -> from newest to oldest
Below a PIPELINERUN node -> from oldest to newest (so one can check which was the first task executed in the pipeline)
> change order behavior based on taskrun node position (#202)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/MirrorStartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartMirrorRunAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/GeneralCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Input.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/AuthenticationStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/InputResourcesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/StartWizard.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/WorkspacesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/StartResourceModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModelFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ResourceConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/RunConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/ConditionConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/PipelineConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/TaskConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/runs/PipelineRunConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/runs/TaskRunConfigurationModel.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConditionConfigurationModelTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModelFactoryTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/PipelineConfigurationModelTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/TaskConfigurationModelTest.java
it resolves #161 
This PR allows users to open the start wizard with data taken from an old *run in two ways
1) A new action belonging to a *run node. It opens up the wizard with data taken from the *run selected. 
If the original pipeline has been updated with new fields, only the ones existing in the *run will be filled in.
If the pipeline has been updated and some fields have been removed, only the ones existing in the pipeline/*run will be filled in.
I called the action `start mirror` but i am not really sure about the naming. Any better idea?
2) The wizard has a new panel (advanced options) which contains an option to take data from a specific *run.
Once a *run is selected in the combobox, the wizard is updated with the values taken from that *run.
The options panel is quite empty …
> Open start wizard with data from previous *run

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/ShowDiagnosticDataAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/resources/META-INF/plugin.xml
It resolves #181 
This is the a very basic implementation of an action which should be useful to debug a *run. 
As an example, i created a pvc with a size which wasn't supported by my cluster (there was no pv available for that size) and so the *run could not be completed but it was stuck in a running mode. 
By using the tkn cli the user doesn't receive any feedback in such cases.
By clicking on the `Show Diagnostic Data` action this is the result. 
I'll try to add more examples as soon as i find them. Any other suggestion for this? @jeffmaury
> Action to take infos regarding resources created by a run

- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TaskAutoInsertHandler.java
it resolves #226 
Now, when using taskRef code completion, the default values (both strings and array) are copied
> add default value with taskRef code completion (#226)

- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Input.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Output.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TektonReferencesInspection.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/VariableReferencesInspector.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ResourceConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/TaskConfigurationModel.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/VariableReferenceInspectorTest.java
- src/test/resources/utils/variableReferenceInspector/pipeline1.yaml
- src/test/resources/utils/variableReferenceInspector/pipeline2.yaml
- src/test/resources/utils/variableReferenceInspector/pipeline3.yaml
- src/test/resources/utils/variableReferenceInspector/pipeline4.yaml
- src/test/resources/utils/variableReferenceInspector/task1.yaml
- src/test/resources/utils/variableReferenceInspector/task2.yaml
- src/test/resources/utils/variableReferenceInspector/task3.yaml
- src/test/resources/utils/variableReferenceInspector/task4.yaml
- src/test/resources/utils/variableReferenceInspector/task5.yaml
it resolves #182 
This patch makes all unused variables being colored in gray so users can easily see if they have some variables that can be removed or that has to be used somewhere. Useful when you copy a pipeline/task from internet/TektonHub and start editing it based on your requirement.
> Grey unused variables

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/editors/TektonFileEditorProvider.java
Fixes #276
In order to test it:
- change to 2020.2 (in gradle.properties)
- open editor on pipeline or task and verify log
> Make editor provider DumbAware

- src/main/java/com/redhat/devtools/intellij/tektoncd/listener/TreeExpansionListener.java
it resolves #275 
The problem here is that the watch is set when a node is actually expanded but its children were already calculated and the user see an old version of them.
E.g in a tree like
```
root
|->namespace
|-> pipelines
|-> pipeline-1
|-> pipeline-2
```
when the tree is created it contains `root`, `namespace` and `pipelines` nodes, with `pipelines` node hidden. When `namespace` is expanded, `pipelines` is made visible and `pipeline-1` and `pipeline-2` are pre-loaded (they are hidden). At this point if something change on cluster (e.g `pipeline-3` is created), the children of pipelines are not updated as this was not expanded and the watch has not been activated.
This is a quick fix. As soon as we start depending on the k8s plugin and we show only the current active namespace we …
> Refresh node before expanding (#275)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/AddTriggerAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/task/CreateTaskRunTemplateAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseWizard.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/CRDHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/DeployHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TreeHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/VirtualFileHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/actions/ActionToRunModel.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilderTest.java
it resolves #289 
As discussed, this patch shows the *run that is going to be created in the preview panel of the start dialog
To be in sync with vscode I also added the action to generate a taskrun template so the user can edit it in the editor. 
Then once the action is clicked a skeleton of the taskRun is opened and it works exactly as the other resources. When the user is ready to save, the IDE asks if it has to be pushed to the cluster.
> Generate taskrun example from task (#289)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartLastRunAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsConfigurable.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsState.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/settings/SettingsView.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubMarketplaceTab.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/NotificationHelper.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
- src/main/resources/META-INF/plugin.xml
it resolves #290 
When enabled, the result of a pipelinerun is displayed as a notification balloon (as in vscode)
The setting is set to enabled, not sure if we want to keep it disabled at start
> display pipelinerun result as notification (#290)

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseWizard.java
it resolves #314 
Now values too long will be written as multilines.
> fix pipeline preview when value is too long (#314)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/LogsBaseAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/logs/ShowLogsAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
it resolves #257 
@jeffmaury for eventiListeners there is no `follow logs` action but they implemented the tail feature which allows to display only the latest rows. E.g `tkn el logs <name> -t 2` -> prints the last 2 rows of the logs.
It's quite useful when there are long logs but how do we want to show this option? Create a new action or to display an input when the `show logs` is clicked?
> Add show logs to eventListener #257

- .github/workflows/draftGenerator.yml
@jeffmaury this is what you asked the other week. It generates a changelog starting from the last release to the latest commit.
Example here https://github.com/lstocchi/intellij-tekton/actions/runs/683320425 , in the bottom you can download the archive containing the draft
> chore: workflow to generate draft changelog

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/DeleteAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/clustertask/FindClusterTaskRefAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/task/FindTaskRefAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/TknAutoInsertHandler.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/DeleteDialog.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/hub/HubModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/WindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/findusage/FindTaskRefPanelBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/findusage/FindWindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/findusage/RefUsage.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/BaseWizard.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/TektonVirtualFileManager.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/WatchHandler.java
- src/main/resources/META-INF/plugin.xml
it resolves #259 .
This patch adds the action to find references of a task/clustertask inside the cluster. 
A tool window is opened in the bottom consisting of a tree that contains all resources that contains a reference to the task/ct. Each resource can be opened in read-only from there and also in the editor, in the classic way, using the `jump to source` action (as IJ does for its `Find Usages` action).
In the delete dialog there is a message to inform the user whenever the resource to be deleted is used somewhere.
> feat(UI): add find task references action (#259)

- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliPipelineTest.java
- src/it/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTaskTest.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/StartAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Input.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/ParametersStep.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
it resolves #313 
I am quite unsure the empty array in yaml is converted correctly but i copied what tekton does. Basically if you pass an empty array to the array param, the pipeline/task will be run like this
```
- name: values
value:
- ""
```
which for me is not an empty array but an array with an empty string as first value. Maybe something to ask to the tekton team.
Other thing to think about is if we want to allow users to start pipelines/tasks with empty string parameters.
With this patch only array parameter accepts an empty value, in a string param the empty value is considered an error.
WDYT? @jeffmaury If we consider that there could be a default value as an empty string it makes sense to remove this check
> fix: Allows parameter array to accept empty array as value (#313)

- src/main/java/com/redhat/devtools/intellij/tektoncd/actions/debug/DebugTaskAction.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/Tkn.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/actions/ActionToRunModel.java
- src/main/resources/META-INF/plugin.xml
> feat: start debug session from task (#470)

- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
it resolves #518 
The problem was that i had number inputs and by minimizing quotes they were written as `value:1` instead of `value"1"`
> fix: error when starting task in debug (#518)

- src/main/java/com/redhat/devtools/intellij/tektoncd/Constants.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/completion/GeneralCompletionProvider.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/inspector/VariableReferencesInspector.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/Workspace.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/wizard/WorkspacesStep.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/YAMLBuilder.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/ResourceConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/RunConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/actions/ActionToRunModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/ConditionConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/PipelineConfigurationModel.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/utils/model/resources/TaskConfigurationModel.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCliTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/tkn/component/field/WorkspaceTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/PipelineConfigurationModelTest.java
- src/test/java/com/redhat/devtools/intellij/tektoncd/utils/model/TaskConfigurationModelTest.java
> feat: add support for optional workspace

- src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/WindowToolFactory.java
- src/main/java/com/redhat/devtools/intellij/tektoncd/validation/TektonSchemasProviderFactory.java
- src/main/resources/META-INF/plugin-json.xml
> fix: prevent plugin exception classloader is not equal to plugin's one

- src/main/resources/META-INF/plugin.xml
> fix: remove overview word from plugin description (#630)

- .github/workflows/changelog.yml
- .github/workflows/ci.yml
- .github/workflows/conventionalCheck.yml
- .github/workflows/draftGenerator.yml
- .github/workflows/release.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
> chore: Pin 3rd-party actions to SHA1

- .github/workflows/IJ.yml
- build.gradle
- gradle.properties
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/redhat/devtools/intellij/tektoncd/completion/GenericCompletionProviderTest.java
Caused following change that requires `sinceIdea` to be bumped to `IU-2022.3`
https://github.com/redhat-developer/intellij-common/pull/219
> chore(skip-release): bump sinceIdea to IU-2022.3
